# Generated by Django 4.0 on 2022-01-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Enter your text')),
            ],
            options={
                'verbose_name': 'AboutUs',
                'verbose_name_plural': 'AboutUs',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Your name')),
                ('email', models.EmailField(max_length=254, verbose_name='You Email')),
                ('message', models.TextField(verbose_name='Your Message')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='DjangoBlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('post_created', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('post_last_updated', models.DateTimeField(auto_now=True, verbose_name='DateTime')),
                ('text', models.TextField(verbose_name='Enter your text')),
                ('file', models.FileField(blank=True, null=True, upload_to='djangoFiles')),
            ],
            options={
                'verbose_name': 'DjangoBlogPost',
                'verbose_name_plural': 'DjangoBlogPosts',
            },
        ),
        migrations.CreateModel(
            name='DLBlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('post_created', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('post_last_updated', models.DateTimeField(auto_now=True, verbose_name='DateTime')),
                ('text', models.TextField(verbose_name='Enter your text')),
                ('file', models.FileField(blank=True, null=True, upload_to='DLFiles')),
            ],
            options={
                'verbose_name': 'DLBlogPost',
                'verbose_name_plural': 'DLBlogPosts',
            },
        ),
        migrations.CreateModel(
            name='MLBlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('post_created', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('post_last_updated', models.DateTimeField(auto_now=True, verbose_name='DateTime')),
                ('text', models.TextField(verbose_name='Enter your text')),
                ('file', models.FileField(blank=True, null=True, upload_to='MLFiles')),
            ],
            options={
                'verbose_name': 'MLBlogPost',
                'verbose_name_plural': 'MLBlogPosts',
            },
        ),
        migrations.CreateModel(
            name='PythonBlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('post_created', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('post_last_updated', models.DateTimeField(auto_now=True, verbose_name='DateTime')),
                ('text', models.TextField(verbose_name='Enter your text')),
                ('file', models.FileField(blank=True, null=True, upload_to='pythonFiles')),
            ],
            options={
                'verbose_name': 'PythonBlogPost',
                'verbose_name_plural': 'PythonBlogPosts',
            },
        ),
    ]
