# Generated by Django 3.2.4 on 2021-06-27 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('status_publish_date', models.DateField()),
            ],
        ),
    ]
