# Generated by Django 3.2.9 on 2021-12-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='everyuserprofile',
            name='user_profile_image',
            field=models.ImageField(default='avater.png', upload_to='profile_images'),
        ),
    ]
