# Generated by Django 4.0 on 2022-01-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_last_update_post_post_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atricals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('artical_created', models.DateField(auto_now_add=True)),
                ('artical_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
