# Generated by Django 4.0.1 on 2022-01-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='userName')),
                ('firstName', models.CharField(max_length=50, verbose_name='firstName')),
                ('lastName', models.CharField(max_length=50, verbose_name='lastName')),
                ('email', models.EmailField(max_length=50, verbose_name='userEmail')),
                ('password1', models.CharField(max_length=50, verbose_name='password')),
                ('password2', models.CharField(max_length=50, verbose_name='confirmPassword')),
            ],
        ),
    ]
