# Generated by Django 4.0.4 on 2022-05-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=150)),
                ('lastName', models.CharField(max_length=150)),
                ('fatherName', models.CharField(max_length=150)),
                ('motherName', models.CharField(max_length=150)),
                ('admissionSession', models.CharField(max_length=150)),
                ('studentID', models.CharField(max_length=150)),
                ('semester', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('mobileNumber', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=50)),
                ('payment', models.CharField(max_length=100)),
                ('formSubmited', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
